### ISSUE TITLE
Add feature to change the Page Number font size.

### ISSUE THREAD

**Issue by erleichdaarchiving** [radius314/bread#41] opened 2018-10-27 14:31 UTC
The page number font size is not adjustable in bread. If it is possible, it would be nice to be able to adjust the page number font size.

We use bread for printing a Multi-Regional Meeting List on full page layout. We had to make everything 2x as large on a full page layout so the printer could then print out the PDF pages to be shot on film and reduced about half the size. This makes the page numbers very small. It is not critical but would be nice if we could change that font size as long as it does not cause other formatting issues.

**Comment by pjaudiomv** [comment] 2018-10-27 14:34
What size is the final meeting list from printer 8.5 x 11? Or 11x17

**Comment by pjaudiomv** [comment] 2018-10-27 14:36
Nerna has their regional meeting directory (500 + meetings) printed on double sided 11x17 and works pretty good. However that's about the limit if we had many more it'd end up being a booklet needing page numbering

**Comment by pjaudiomv** [comment] 2018-10-27 22:00
@erleichdaarchiving  submitted pull request for this, was pretty easy add.

**Comment by radius314** [comment] 2018-10-28 03:58
released in bread 1.7.0

**Closed by radius314** 2018-10-28 03:58 UTC
Labels: enhancement

**Comment by erleichdaarchiving** [comment] 2018-10-28 04:05
Upgrading to bread 1.70 seems to be failing on our install. You click upgrade, it appears to complete but when you go to other menu item the update icon reappears. Tried upgrading several times, each time it will still show the update is available after you go to away from plugins and return.

Trying to run the plugin gives this error:

`Fatal error: Uncaught exception 'Mpdf\MpdfException' with message 'Cannot write to an undeclared property Mpdf\Mpdf::$progressBar' in /home4/eparnaws/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Strict.php:44 Stack trace: #0 /home4/eparnaws/public_html/wp-content/plugins/bread/bmlt-meeting-list.php(646): Mpdf\Mpdf->__set('progressBar', 0) #1 /home4/eparnaws/public_html/wp-content/plugins/bread/bmlt-meeting-list.php(55): Bread->bmlt_meeting_list() #2 /home4/eparnaws/public_html/wp-content/plugins/bread/bmlt-meeting-list.php(2068): Bread->__construct() #3 /home4/eparnaws/public_html/wp-settings.php(305): include_once('/home4/eparnaws...') #4 /home4/eparnaws/public_html/wp-config.php(89): require_once('/home4/eparnaws...') #5 /home4/eparnaws/public_html/wp-load.php(37): require_once('/home4/eparnaws...') #6 /home4/eparnaws/public_html/wp-blog-header.php(13): require_once('/home4/eparnaws...') #7 /home4/eparnaws/public_html/index.php(17): require('/home4/eparnaws...') #8 {main} thrown in /home4/eparnaws/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Strict.php on line 44`

**Comment by radius314** [comment] 2018-10-28 04:07
Ok I think I know what the issue is.  Working on a fix.

**Comment by radius314** [comment] 2018-10-28 05:07
Should be fixed in bread 1.7.3, please try to update.

**Comment by erleichdaarchiving** [comment] 2018-10-28 12:30
1.7.3 fixed this isse. Thank you!

**Comment by radius314** [comment] 2018-10-28 14:45
Good to hear
