### ISSUE TITLE
Spaces being interpreted as ^A

### ISSUE THREAD

**Issue by webfacilitator** [radius314/bread#17] opened 2018-05-28 14:46 UTC
![image](https://user-images.githubusercontent.com/24917511/40619645-dbd69bfc-6263-11e8-957c-5897a20635bb.png)

Error reported by PR Facilitator for North Atlanta Area regarding the Metro Atlanta Sub-Region's meeting list not running at https://metro.grscna.com/?current-meeting-list=1

Problem confirmed.  Uninstalled and reinstalled bread plugin.  Meeting ran but ^A appeared in every place where a space had been inserted in Meeting List format. Base font switched to Arial.  All pre-existing text highlighted and changed to Arial font.  Problem still there.  Forced to remove all spaces, even layout preferable with extra lines or spaces.

**Comment by radius314** [comment] 2018-05-28 14:47
@webfacilitator, I could not reproduce the issue with JSON settings file that you attached.  Can you reproduce the issue and then re-export and attach to this ticket?

**Comment by radius314** [comment] 2018-05-28 14:48
In addition, what are the repro steps to get this error message?  Your description does not seem to indicate at what point this error appeared.

**Comment by webfacilitator** [comment] 2018-05-29 13:49
1) Import the json meeting list settings file under Backup/Restore of Meeting List plugin
2) Go to Front Page tab under Meeting List
3) Add a space before logo (with logo selected press enter)
4) Save
5) Generate Meeting List
6) ^A appears at top of meeting list PDF

[metro-atlanta-georgia-sub-region-meeting-list-settings-05-29-2018.zip](https://github.com/radius314/bread/files/2048440/metro-atlanta-georgia-sub-region-meeting-list-settings-05-29-2018.zip)

**Comment by pjaudiomv** [comment] 2018-05-29 14:58
weird I was able to reproduce the problem organically but not the php error, it seems if you change the base font to anything but arial it will fix the ^A issue

**Comment by pjaudiomv** [comment] 2018-05-29 17:07
this is only happening when using core fonts, $mode = 'c'. I added the individual ttf files and kept mode set to's' an dit works fine. something with the way those core font php files are doing character assigning may be the issue but not sure. either way if we move away from using core fonts and just include the actual font files for different font types this will fix the issue

**Comment by radius314** [comment] 2018-05-30 01:46
correct, core fonts do not support unicode.  the goal here was to do something lightweight.

**Comment by radius314** [comment] 2018-08-03 02:36
will be released with bread 1.5.0

**Comment by radius314** [comment] 2018-08-03 14:14
please verify that this is fixed in bread 1.5.1

**Comment by radius314** [comment] 2018-08-07 21:56
Looking for verification on this.

**Comment by pjaudiomv** [comment] 2018-08-07 22:00
I'm gonna verify it there's some weird stuff going on but I think it's mpdf not bread. If you choose times. Anything that's not bold shows up as times new Roman and if it is bold it shows up as just times. I even tried swapping out html strong tag for bold or using css font-weight. Nothing changed it.

**Comment by pjaudiomv** [comment] 2018-08-07 22:00
All other fonts behave normal

**Comment by pjaudiomv** [comment] 2018-08-07 22:02
The only thing I haven't tried was setting the base font to be times new Roman

**Comment by pjaudiomv** [comment] 2018-08-07 22:16
Regardless Spaces thing is fine now

**Closed** 2018-08-07 23:33 UTC
Labels: bug
